[project]
name = "Kangnam's Tool Box"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.1",
    "opencv-python>=4.11.0.86",
    "torch>=2.7.1",
    "torchvision>=0.22.1",
]

[dependency-groups]
dev = [
    "matplotlib>=3.10.3",
]
